/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/gltf/ModelEuropProduit/europ.gltf -r public 
*/
import { useGLTF } from '@react-three/drei'

export function Europ(props) {
  const { nodes, materials } = useGLTF('./gltf/ModelEuropProduit/europ.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-10.395, -0.6, 2.527]} scale={0.0003} >
        <mesh geometry={nodes.PRODUITEUROPALU_1.geometry} material={materials['METAL_-_ACIER_INOXYDABLE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_2.geometry} material={materials['METAL_-_ACIER_INOXYDABLE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_3.geometry} material={materials['METAL_-_ACIER_INOXYDABLE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_4.geometry} material={materials['ENDUIT_-_BLANC_NATURE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_5.geometry} material={materials['ENDUIT_-_PLATRE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_6.geometry} material={materials['BRIQUE_-_BLANCHE_NATURELLE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_7.geometry} material={materials['PLATRE_-_BRIQUES_OU_CARREAUX_D.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_8.geometry} material={materials['METAL_-_ALUMINIUM_GRIS_FONCE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_9.geometry} material={materials['TRANSP__-_VERRE_CLAIR__RAPIDE_.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_10.geometry} material={materials['METAL_-_ALUMINIUM_GRIS_ANTHRAC.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_11.geometry} material={materials['BOIS_-_PIN_GRANULEUX_HORIZONTA.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_12.geometry} material={materials['EI704_EICHE__INTERNORM_.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_13.geometry} material={materials['FINE_UPHOLSTERY_LIGHT_BROWN__F.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_14.geometry} material={materials['TOP_FROSTED_GLASS__FORAFORM_.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_15.geometry} material={materials['EI703_EICHE__INTERNORM_.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_16.geometry} material={materials['PEINTURE_-_BLEU_COBALT.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_17.geometry} material={materials['METAL_-_ALUMINIUM.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_18.geometry} material={materials['METAL_-_ALUMINIUM.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_19.geometry} material={materials['PEINTURE_-_BLANC_TITANIUM.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_20.geometry} material={materials['AIR_-_VIDE_D_AIR.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_21.geometry} material={materials['METAL_-_ALUMINIUM_ROUGE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_22.geometry} material={materials['OREGON_DECOR__INTERNORM_.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_23.geometry} material={materials['MARBRE_-_NOIR.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_24.geometry} material={materials['PEINTURE_-_NOIR.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_25.geometry} material={materials['PEINTURE_-_CARMIN.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_26.geometry} material={materials['APPAREILLAGE_-_GRANIT.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_27.geometry} material={materials['ENV__-_TERRE_.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_28.geometry} material={materials['TRANSP__-_VERRE_BLEUTE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_29.geometry} material={materials['LAMINATE_WHITE_411__FORAFORM_.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_30.geometry} material={materials['EI700_EICHE__INTERNORM_.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_31.geometry} material={materials['EI701_EICHE__INTERNORM_.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_32.geometry} material={materials['TRANSP__-_VERRE_VERT.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_33.geometry} material={materials['HM906__ALUMINIUM__NATUR__INTER.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_34.geometry} material={materials['PEINTURE_-_BLANC_BRILLANT.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_35.geometry} material={materials['180M_CREME__RAL1015M__INTERNOR.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_36.geometry} material={materials['ETANCHEITE_-_BITUME.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_37.geometry} material={materials['METAL_-_CHROME.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_38.geometry} material={materials['HM735__HELLGRAU__INTERNORM_.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_39.geometry} material={materials['BEIGE__NCS_S_4005-Y20R___FORAF.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_40.geometry} material={materials['PURPLE__NCS_S_7020-R40B___FORA.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_41.geometry} material={materials['METAL_-_ALUMINIUM_BEIGE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_42.geometry} material={materials['METAL-INOX.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_43.geometry} material={materials['METAL-INOX.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_44.geometry} material={materials['METAL-INOX.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_45.geometry} material={materials['METAL-ALUMINIUM.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_46.geometry} material={materials['METAL-ALUMINIUM_3.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_47.geometry} material={materials['METAL-ZINC_COPIE.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_48.geometry} material={materials['METAL-NICKEL.001']} />
        <mesh geometry={nodes.PRODUITEUROPALU_49.geometry} material={materials['METAL-LAITON.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/gltf/ModelEuropProduit/europ.gltf')
