/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/gltf/ModelEurop/europ.gltf -j -r public 
*/

import { useGLTF } from '@react-three/drei'

export function Europ2(props) {
  const { nodes, materials } = useGLTF('/gltf/ModelEurop/europ.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-10.395, -0.6, 2.527]} scale={0.0003}>
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_1.geometry} material={materials['PEINTURE_-_BLANC_TITANIUM']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_2.geometry} material={materials['ENDUIT_-_PLATRE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_3.geometry} material={materials['BRIQUE_-_BLANCHE_NATURELLE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_4.geometry} material={materials['ENDUIT_-_BLANC_NATURE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_5.geometry} material={materials['PEINTURE_-_NOIR']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_6.geometry} material={materials['APPAREILLAGE_-_GRANIT']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_7.geometry} material={materials['TRANSP__-_VERRE_CLAIR__RAPIDE_']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_8.geometry} material={materials['METAL_-_ACIER_INOXYDABLE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_9.geometry} material={materials['METAL_-_ACIER_INOXYDABLE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_10.geometry} material={materials['METAL_-_ACIER_INOXYDABLE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_11.geometry} material={materials['METAL_-_ALUMINIUM_GRIS_FONCE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_12.geometry} material={materials['METAL_-_ALUMINIUM_GRIS_ANTHRAC']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_13.geometry} material={materials['BOIS_-_PIN_GRANULEUX_HORIZONTA']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_14.geometry} material={materials.EI704_EICHE__INTERNORM_} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_15.geometry} material={materials.FINE_UPHOLSTERY_LIGHT_BROWN__F} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_16.geometry} material={materials.TOP_FROSTED_GLASS__FORAFORM_} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_17.geometry} material={materials.EI703_EICHE__INTERNORM_} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_18.geometry} material={materials['PEINTURE_-_BLEU_COBALT']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_19.geometry} material={materials['METAL_-_ALUMINIUM']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_20.geometry} material={materials['METAL_-_ALUMINIUM']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_21.geometry} material={materials['AIR_-_VIDE_D_AIR']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_22.geometry} material={materials['PLATRE_-_BRIQUES_OU_CARREAUX_D']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_23.geometry} material={materials['METAL_-_ALUMINIUM_ROUGE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_24.geometry} material={materials.OREGON_DECOR__INTERNORM_} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_25.geometry} material={materials['MARBRE_-_NOIR']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_26.geometry} material={materials['PEINTURE_-_CARMIN']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_27.geometry} material={materials['ENDUIT_-_JAUNE_NATURE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_28.geometry} material={materials.EDELWEI___INTERNORM_} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_29.geometry} material={materials['ENV__-_TERRE_']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_30.geometry} material={materials['180M_CREME__RAL1015M__INTERNOR']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_31.geometry} material={materials.EI701_EICHE__INTERNORM_} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_32.geometry} material={materials.LAMINATE_WHITE_411__FORAFORM_} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_33.geometry} material={materials.EI700_EICHE__INTERNORM_} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_34.geometry} material={materials['TRANSP__-_VERRE_BLEUTE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_35.geometry} material={materials['TRANSP__-_VERRE_VERT']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_36.geometry} material={materials['PEINTURE_-_BLANC_BRILLANT']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_37.geometry} material={materials.HM906__ALUMINIUM__NATUR__INTER} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_38.geometry} material={materials.ROUGH_UPHOLSTERY_SAND__FORAFOR} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_39.geometry} material={materials['METAL_-_CHROME']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_40.geometry} material={materials.HM735__HELLGRAU__INTERNORM_} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_41.geometry} material={materials['BEIGE__NCS_S_4005-Y20R___FORAF']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_42.geometry} material={materials['PURPLE__NCS_S_7020-R40B___FORA']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_43.geometry} material={materials['METAL_-_ALUMINIUM_BEIGE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_44.geometry} material={materials['METAL-INOX']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_45.geometry} material={materials['METAL-INOX']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_46.geometry} material={materials['METAL-INOX']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_47.geometry} material={materials['METAL-ALUMINIUM']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_48.geometry} material={materials['METAL-NICKEL']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_49.geometry} material={materials['METAL-ZINC_COPIE']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_50.geometry} material={materials['METAL-LAITON']} />
        <mesh geometry={nodes.PRODUITEUROPALUMODIF25102023_51.geometry} material={materials['METAL-ALUMINIUM_3']} />
      </group>
    </group>
  )
}

useGLTF.preload('/gltf/ModelEurop/europ.gltf')
